<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program [
<!ATTLIST program
   name CDATA #IMPLIED>
<!ELEMENT program (cfg*)>
<!ATTLIST cfg
  id ID #REQUIRED
  main CDATA #IMPLIED
  name CDATA #IMPLIED>
<!ELEMENT cfg (bb+)>
<!ATTLIST bb
   id ID #REQUIRED>
<!ELEMENT bb (prec?,inst*,succ?)>
<!ELEMENT prec (link+)>
<!ELEMENT succ (link+)>
<!ATTLIST link
  type (taken|nottaken|call) #REQUIRED
  cfg CDATA #REQUIRED
  bb IDREF #REQUIRED>
<!ELEMENT link EMPTY>
<!ATTLIST inst
   addr CDATA #REQUIRED
   instr CDATA #IMPLIED>
<!ELEMENT inst EMPTY>
]>
<program name="bubblesort">
  <cfg id="1" name="group_number">
    <bb id="1">
      <inst addr="0x8170" instr="stmdb sp!, {r4, r5, r6, r7, r8, r9, sl, lr}"/>
      <inst addr="0x8174" instr="mov r4, r0"/>
      <inst addr="0x8176" instr="add r7, sp, #0"/>
      <inst addr="0x8178" instr="mov r0, r3"/>
      <inst addr="0x817a" instr="mov r6, r3"/>
      <inst addr="0x817c" instr="mov r9, r2"/>
      <inst addr="0x817e" instr="mov r8, r1"/>
      <inst addr="0x8180" instr="blx fdc0 strlen"/>
      <inst addr="0x8184" instr="ldrb.w r5, [r9]"/>
      <inst addr="0x8188" instr="subs r3, r5, #1"/>
      <inst addr="0x818a" instr="uxtb r3, r3"/>
      <inst addr="0x818c" instr="cmp r3, #253 ; 0xfd"/>
      <inst addr="0x818e" instr="mov sl, r0"/>
      <inst addr="0x8190" instr="bhi.n 8206 group_number+0x96"/>
      <succ>
        <link type="taken" cfg="1" bb="14"/>
        <link type="nottaken" cfg="1" bb="2"/>
      </succ>
    </bb>
    <bb id="2">
      <inst addr="0x8192" instr="rsb r2, r4, r8"/>
      <inst addr="0x8196" instr="mov r1, r4"/>
      <inst addr="0x8198" instr="add.w r3, r2, #14"/>
      <inst addr="0x819c" instr="mov r4, r8"/>
      <inst addr="0x819e" instr="bic.w r3, r3, #7"/>
      <inst addr="0x81a2" instr="add.w r9, r9, #1"/>
      <inst addr="0x81a6" instr="sub.w sp, sp, r3"/>
      <inst addr="0x81aa" instr="mov r0, sp"/>
      <inst addr="0x81ac" instr="mov r8, sp"/>
      <inst addr="0x81ae" instr="bl 104b0 __mempcpy"/>
      <succ>
        <link type="nottaken" cfg="1" bb="3"/>
        <link type="call" cfg="156" bb="2878"/>
      </succ>
    </bb>
    <bb id="3">
      <inst addr="0x81b2" instr="b.n 8202 group_number+0x92"/>
      <succ>
        <link type="taken" cfg="1" bb="13"/>
      </succ>
    </bb>
    <bb id="4">
      <inst addr="0x81b4" instr="ldrb.w r3, [r0, #-1]!"/>
      <inst addr="0x81b8" instr="subs r2, r4, #1"/>
      <inst addr="0x81ba" instr="subs r5, #1"/>
      <inst addr="0x81bc" instr="strb.w r3, [r4, #-1]"/>
      <inst addr="0x81c0" instr="bne.n 8200 group_number+0x90"/>
      <succ>
        <link type="taken" cfg="1" bb="12"/>
        <link type="nottaken" cfg="1" bb="5"/>
      </succ>
    </bb>
    <bb id="5">
      <inst addr="0x81c2" instr="cmp r0, r8"/>
      <inst addr="0x81c4" instr="bls.n 8200 group_number+0x90"/>
      <succ>
        <link type="taken" cfg="1" bb="12"/>
        <link type="nottaken" cfg="1" bb="6"/>
      </succ>
    </bb>
    <bb id="6">
      <inst addr="0x81c6" instr="rsb r4, sl, r4"/>
      <inst addr="0x81ca" instr="mov r3, sl"/>
      <succ>
        <link type="nottaken" cfg="1" bb="7"/>
      </succ>
    </bb>
    <bb id="7">
      <inst addr="0x81cc" instr="subs r3, #1"/>
      <inst addr="0x81ce" instr="subs r2, #1"/>
      <inst addr="0x81d0" instr="adds r1, r4, r3"/>
      <inst addr="0x81d2" instr="cmp r3, #0"/>
      <inst addr="0x81d4" instr="ldrb r5, [r6, r3]"/>
      <inst addr="0x81d6" instr="strb.w r5, [r1, #-1]"/>
      <inst addr="0x81da" instr="bgt.n 81cc group_number+0x5c"/>
      <succ>
        <link type="taken" cfg="1" bb="7"/>
        <link type="nottaken" cfg="1" bb="8"/>
      </succ>
    </bb>
    <bb id="8">
      <inst addr="0x81dc" instr="ldrb.w r5, [r9]"/>
      <inst addr="0x81e0" instr="cmp r5, #255 ; 0xff"/>
      <inst addr="0x81e2" instr="bne.n 81f4 group_number+0x84"/>
      <succ>
        <link type="taken" cfg="1" bb="10"/>
        <link type="nottaken" cfg="1" bb="9"/>
      </succ>
    </bb>
    <bb id="9">
      <inst addr="0x81e4" instr="mov r4, r2"/>
      <inst addr="0x81e6" instr="ldrb.w r3, [r0, #-1]!"/>
      <inst addr="0x81ea" instr="cmp r8, r0"/>
      <inst addr="0x81ec" instr="strb.w r3, [r4, #-1]!"/>
      <inst addr="0x81f0" instr="bcc.n 81e6 group_number+0x76"/>
      <inst addr="0x81f2" instr="b.n 8206 group_number+0x96"/>
      <succ>
        <link type="taken" cfg="1" bb="14"/>
      </succ>
    </bb>
    <bb id="10">
      <inst addr="0x81f4" instr="cbz r5, 81fc group_number+0x8c"/>
      <inst addr="0x81f6" instr="add.w r9, r9, #1"/>
      <inst addr="0x81fa" instr="b.n 8200 group_number+0x90"/>
      <succ>
        <link type="taken" cfg="1" bb="12"/>
      </succ>
    </bb>
    <bb id="12">
      <inst addr="0x8200" instr="mov r4, r2"/>
      <succ>
        <link type="nottaken" cfg="1" bb="13"/>
      </succ>
    </bb>
    <bb id="13">
      <inst addr="0x8202" instr="cmp r0, r8"/>
      <inst addr="0x8204" instr="bhi.n 81b4 group_number+0x44"/>
      <succ>
        <link type="taken" cfg="1" bb="4"/>
        <link type="nottaken" cfg="1" bb="14"/>
      </succ>
    </bb>
    <bb id="14">
      <inst addr="0x8206" instr="mov r0, r4"/>
      <inst addr="0x8208" instr="mov sp, r7"/>
      <inst addr="0x820a" instr="ldmia.w sp!, {r4, r5, r6, r7, r8, r9, sl, pc}"/>
      <inst addr="0x820e" instr="nop"/>
      <succ>
      </succ>
    </bb>
  </cfg>
  <cfg id="2" name="_i18n_number_rewrite">
    <bb id="15">
      <inst addr="0x8210" instr="stmdb sp!, {r4, r5, r6, r7, r8, r9, sl, fp, lr}"/>
      <inst addr="0x8214" instr="sub sp, #52 ; 0x34"/>
      <inst addr="0x8216" instr="mov r4, r0"/>
      <inst addr="0x8218" instr="add r7, sp, #0"/>
      <inst addr="0x821a" instr="ldr r0, [pc, #336] ; (836c _i18n_number_rewrite+0x15c)"/>
      <inst addr="0x821c" instr="mov r6, r2"/>
      <inst addr="0x821e" instr="mov r8, r1"/>
      <inst addr="0x8220" instr="bl 273f0 __wctrans"/>
      <succ>
        <link type="nottaken" cfg="2" bb="16"/>
        <link type="call" cfg="491" bb="9610"/>
      </succ>
    </bb>
    <bb id="16">
      <inst addr="0x8224" instr="mov r1, r0"/>
      <inst addr="0x8226" instr="mov r5, r0"/>
      <inst addr="0x8228" instr="movs r0, #46 ; 0x2e"/>
      <inst addr="0x822a" instr="bl 27440 __towctrans"/>
      <succ>
        <link type="nottaken" cfg="2" bb="17"/>
        <link type="call" cfg="492" bb="9616"/>
      </succ>
    </bb>
    <bb id="17">
      <inst addr="0x822e" instr="mov r1, r5"/>
      <inst addr="0x8230" instr="mov sl, r0"/>
      <inst addr="0x8232" instr="movs r0, #44 ; 0x2c"/>
      <inst addr="0x8234" instr="bl 27440 __towctrans"/>
      <succ>
        <link type="nottaken" cfg="2" bb="18"/>
        <link type="call" cfg="492" bb="9616"/>
      </succ>
    </bb>
    <bb id="18">
      <inst addr="0x8238" instr="mov r9, r0"/>
      <inst addr="0x823a" instr="cbz r5, 8292 _i18n_number_rewrite+0x82"/>
      <inst addr="0x823c" instr="mov r1, sl"/>
      <inst addr="0x823e" instr="mov r0, r7"/>
      <inst addr="0x8240" instr="add.w r2, r7, #40 ; 0x28"/>
      <inst addr="0x8244" instr="mov.w sl, #0"/>
      <inst addr="0x8248" instr="str.w sl, [r7, #40] ; 0x28"/>
      <inst addr="0x824c" instr="str.w sl, [r7, #44] ; 0x2c"/>
      <inst addr="0x8250" instr="bl 22054 __wcrtomb"/>
      <succ>
        <link type="nottaken" cfg="2" bb="19"/>
        <link type="call" cfg="411" bb="8111"/>
      </succ>
    </bb>
    <bb id="19">
      <inst addr="0x8254" instr="mov r3, sl"/>
      <inst addr="0x8256" instr="adds r1, r0, #1"/>
      <inst addr="0x8258" instr="bne.n 8260 _i18n_number_rewrite+0x50"/>
      <succ>
        <link type="taken" cfg="2" bb="21"/>
        <link type="nottaken" cfg="2" bb="20"/>
      </succ>
    </bb>
    <bb id="20">
      <inst addr="0x825a" instr="movs r2, #46 ; 0x2e"/>
      <inst addr="0x825c" instr="strh r2, [r7, #0]"/>
      <inst addr="0x825e" instr="b.n 826a _i18n_number_rewrite+0x5a"/>
      <succ>
        <link type="taken" cfg="2" bb="22"/>
      </succ>
    </bb>
    <bb id="21">
      <inst addr="0x8260" instr="add.w r2, r7, #48 ; 0x30"/>
      <inst addr="0x8264" instr="adds r0, r2, r0"/>
      <inst addr="0x8266" instr="strb.w sl, [r0, #-48]"/>
      <succ>
        <link type="nottaken" cfg="2" bb="22"/>
      </succ>
    </bb>
    <bb id="22">
      <inst addr="0x826a" instr="add.w r2, r7, #40 ; 0x28"/>
      <inst addr="0x826e" instr="add.w r0, r7, #20"/>
      <inst addr="0x8272" instr="mov r1, r9"/>
      <inst addr="0x8274" instr="str r3, [r7, #40] ; 0x28"/>
      <inst addr="0x8276" instr="str r3, [r7, #44] ; 0x2c"/>
      <inst addr="0x8278" instr="bl 22054 __wcrtomb"/>
      <succ>
        <link type="nottaken" cfg="2" bb="23"/>
        <link type="call" cfg="411" bb="8111"/>
      </succ>
    </bb>
    <bb id="23">
      <inst addr="0x827c" instr="adds r2, r0, #1"/>
      <inst addr="0x827e" instr="bne.n 8286 _i18n_number_rewrite+0x76"/>
      <succ>
        <link type="taken" cfg="2" bb="25"/>
        <link type="nottaken" cfg="2" bb="24"/>
      </succ>
    </bb>
    <bb id="24">
      <inst addr="0x8280" instr="movs r3, #44 ; 0x2c"/>
      <inst addr="0x8282" instr="strh r3, [r7, #20]"/>
      <inst addr="0x8284" instr="b.n 8292 _i18n_number_rewrite+0x82"/>
      <succ>
        <link type="taken" cfg="2" bb="26"/>
      </succ>
    </bb>
    <bb id="25">
      <inst addr="0x8286" instr="add.w r3, r7, #48 ; 0x30"/>
      <inst addr="0x828a" instr="adds r0, r3, r0"/>
      <inst addr="0x828c" instr="movs r3, #0"/>
      <inst addr="0x828e" instr="strb.w r3, [r0, #-28]"/>
      <succ>
        <link type="nottaken" cfg="2" bb="26"/>
      </succ>
    </bb>
    <bb id="26">
      <inst addr="0x8292" instr="rsb r8, r4, r8"/>
      <inst addr="0x8296" instr="cmp.w r8, #4096 ; 0x1000"/>
      <inst addr="0x829a" instr="bls.n 82aa _i18n_number_rewrite+0x9a"/>
      <succ>
        <link type="taken" cfg="2" bb="29"/>
        <link type="nottaken" cfg="2" bb="27"/>
      </succ>
    </bb>
    <bb id="27">
      <inst addr="0x829c" instr="mov r0, r8"/>
      <inst addr="0x829e" instr="bl 11b50 __libc_alloca_cutoff"/>
      <succ>
        <link type="nottaken" cfg="2" bb="28"/>
        <link type="call" cfg="197" bb="3335"/>
      </succ>
    </bb>
    <bb id="28">
      <inst addr="0x82a2" instr="adds r0, #0"/>
      <inst addr="0x82a4" instr="it ne"/>
      <inst addr="0x82a6" instr="movne r0, #1"/>
      <inst addr="0x82a8" instr="b.n 82ac _i18n_number_rewrite+0x9c"/>
      <succ>
        <link type="taken" cfg="2" bb="30"/>
      </succ>
    </bb>
    <bb id="29">
      <inst addr="0x82aa" instr="movs r0, #1"/>
      <succ>
        <link type="nottaken" cfg="2" bb="30"/>
      </succ>
    </bb>
    <bb id="30">
      <inst addr="0x82ac" instr="uxtb.w sl, r0"/>
      <inst addr="0x82b0" instr="cmp.w sl, #0"/>
      <inst addr="0x82b4" instr="beq.n 82c6 _i18n_number_rewrite+0xb6"/>
      <succ>
        <link type="taken" cfg="2" bb="32"/>
        <link type="nottaken" cfg="2" bb="31"/>
      </succ>
    </bb>
    <bb id="31">
      <inst addr="0x82b6" instr="add.w r3, r8, #14"/>
      <inst addr="0x82ba" instr="bic.w r3, r3, #7"/>
      <inst addr="0x82be" instr="sub.w sp, sp, r3"/>
      <inst addr="0x82c2" instr="mov r9, sp"/>
      <inst addr="0x82c4" instr="b.n 82d2 _i18n_number_rewrite+0xc2"/>
      <succ>
        <link type="taken" cfg="2" bb="34"/>
      </succ>
    </bb>
    <bb id="32">
      <inst addr="0x82c6" instr="mov r0, r8"/>
      <inst addr="0x82c8" instr="bl e7f8 __libc_malloc"/>
      <succ>
        <link type="nottaken" cfg="2" bb="33"/>
        <link type="call" cfg="130" bb="2162"/>
      </succ>
    </bb>
    <bb id="33">
      <inst addr="0x82cc" instr="mov r9, r0"/>
      <inst addr="0x82ce" instr="cmp r0, #0"/>
      <inst addr="0x82d0" instr="beq.n 835e _i18n_number_rewrite+0x14e"/>
      <succ>
        <link type="taken" cfg="2" bb="49"/>
        <link type="nottaken" cfg="2" bb="34"/>
      </succ>
    </bb>
    <bb id="34">
      <inst addr="0x82d2" instr="mov r1, r4"/>
      <inst addr="0x82d4" instr="mov r2, r8"/>
      <inst addr="0x82d6" instr="mov r0, r9"/>
      <inst addr="0x82d8" instr="mov r4, r6"/>
      <inst addr="0x82da" instr="bl 104b0 __mempcpy"/>
      <succ>
        <link type="nottaken" cfg="2" bb="35"/>
        <link type="call" cfg="156" bb="2878"/>
      </succ>
    </bb>
    <bb id="35">
      <inst addr="0x82de" instr="mrc 15, 0, fp, cr13, cr0, {3}"/>
      <inst addr="0x82e2" instr="mov r8, r0"/>
      <inst addr="0x82e4" instr="b.n 834a _i18n_number_rewrite+0x13a"/>
      <succ>
        <link type="taken" cfg="2" bb="47"/>
      </succ>
    </bb>
    <bb id="47">
      <inst addr="0x834a" instr="add.w r8, r8, #4294967295 ; 0xffffffff"/>
      <inst addr="0x834e" instr="cmp r8, r9"/>
      <inst addr="0x8350" instr="bcs.n 82e6 _i18n_number_rewrite+0xd6"/>
      <inst addr="0x8352" instr="cmp.w sl, #0"/>
      <inst addr="0x8356" instr="bne.n 835e _i18n_number_rewrite+0x14e"/>
      <succ>
        <link type="taken" cfg="2" bb="49"/>
        <link type="nottaken" cfg="2" bb="48"/>
      </succ>
    </bb>
    <bb id="48">
      <inst addr="0x8358" instr="mov r0, r9"/>
      <inst addr="0x835a" instr="bl ec9c __cfree"/>
      <succ>
        <link type="nottaken" cfg="2" bb="49"/>
        <link type="call" cfg="134" bb="2289"/>
      </succ>
    </bb>
    <bb id="49">
      <inst addr="0x835e" instr="mov r0, r4"/>
      <inst addr="0x8360" instr="add.w r7, r7, #52 ; 0x34"/>
      <inst addr="0x8364" instr="mov sp, r7"/>
      <inst addr="0x8366" instr="ldmia.w sp!, {r4, r5, r6, r7, r8, r9, sl, fp, pc}"/>
      <inst addr="0x836a" instr="nop"/>
      <inst addr="0x836c" instr=".word 0x0004dce0"/>
      <inst addr="0x8370" instr=".word 0x00061d44"/>
      <succ>
      </succ>
    </bb>
  </cfg>
  <cfg id="3" name="_i18n_number_rewrite_3">
    <bb id="50">
      <inst addr="0x8374" instr="stmdb sp!, {r4, r5, r6, r7, r8, r9, sl, fp, lr}"/>
      <inst addr="0x8378" instr="sub sp, #52 ; 0x34"/>
      <inst addr="0x837a" instr="mov r4, r0"/>
      <inst addr="0x837c" instr="add r7, sp, #0"/>
      <inst addr="0x837e" instr="ldr r0, [pc, #336] ; (84d0 _i18n_number_rewrite+0x15c)"/>
      <inst addr="0x8380" instr="mov r6, r2"/>
      <inst addr="0x8382" instr="mov r8, r1"/>
      <inst addr="0x8384" instr="bl 273f0 __wctrans"/>
      <succ>
        <link type="nottaken" cfg="3" bb="51"/>
        <link type="call" cfg="491" bb="9610"/>
      </succ>
    </bb>
    <bb id="51">
      <inst addr="0x8388" instr="mov r1, r0"/>
      <inst addr="0x838a" instr="mov r5, r0"/>
      <inst addr="0x838c" instr="movs r0, #46 ; 0x2e"/>
      <inst addr="0x838e" instr="bl 27440 __towctrans"/>
      <succ>
        <link type="nottaken" cfg="3" bb="52"/>
        <link type="call" cfg="492" bb="9616"/>
      </succ>
    </bb>
    <bb id="52">
      <inst addr="0x8392" instr="mov r1, r5"/>
      <inst addr="0x8394" instr="mov sl, r0"/>
      <inst addr="0x8396" instr="movs r0, #44 ; 0x2c"/>
      <inst addr="0x8398" instr="bl 27440 __towctrans"/>
      <succ>
        <link type="nottaken" cfg="3" bb="53"/>
        <link type="call" cfg="492" bb="9616"/>
      </succ>
    </bb>
    <bb id="53">
      <inst addr="0x839c" instr="mov r9, r0"/>
      <inst addr="0x839e" instr="cbz r5, 83f6 _i18n_number_rewrite+0x82"/>
      <inst addr="0x83a0" instr="mov r1, sl"/>
      <inst addr="0x83a2" instr="add.w r2, r7, #40 ; 0x28"/>
      <inst addr="0x83a6" instr="mov r0, r7"/>
      <inst addr="0x83a8" instr="mov.w sl, #0"/>
      <inst addr="0x83ac" instr="str.w sl, [r7, #40] ; 0x28"/>
      <inst addr="0x83b0" instr="str.w sl, [r7, #44] ; 0x2c"/>
      <inst addr="0x83b4" instr="bl 22054 __wcrtomb"/>
      <succ>
        <link type="nottaken" cfg="3" bb="54"/>
        <link type="call" cfg="411" bb="8111"/>
      </succ>
    </bb>
    <bb id="54">
      <inst addr="0x83b8" instr="mov r3, sl"/>
      <inst addr="0x83ba" instr="adds r2, r0, #1"/>
      <inst addr="0x83bc" instr="bne.n 83c4 _i18n_number_rewrite+0x50"/>
      <succ>
        <link type="taken" cfg="3" bb="56"/>
        <link type="nottaken" cfg="3" bb="55"/>
      </succ>
    </bb>
    <bb id="55">
      <inst addr="0x83be" instr="movs r2, #46 ; 0x2e"/>
      <inst addr="0x83c0" instr="strh r2, [r7, #0]"/>
      <inst addr="0x83c2" instr="b.n 83ce _i18n_number_rewrite+0x5a"/>
      <succ>
        <link type="taken" cfg="3" bb="57"/>
      </succ>
    </bb>
    <bb id="56">
      <inst addr="0x83c4" instr="add.w r2, r7, #48 ; 0x30"/>
      <inst addr="0x83c8" instr="adds r0, r2, r0"/>
      <inst addr="0x83ca" instr="strb.w sl, [r0, #-48]"/>
      <succ>
        <link type="nottaken" cfg="3" bb="57"/>
      </succ>
    </bb>
    <bb id="57">
      <inst addr="0x83ce" instr="add.w r0, r7, #20"/>
      <inst addr="0x83d2" instr="mov r1, r9"/>
      <inst addr="0x83d4" instr="add.w r2, r7, #40 ; 0x28"/>
      <inst addr="0x83d8" instr="str r3, [r7, #40] ; 0x28"/>
      <inst addr="0x83da" instr="str r3, [r7, #44] ; 0x2c"/>
      <inst addr="0x83dc" instr="bl 22054 __wcrtomb"/>
      <succ>
        <link type="nottaken" cfg="3" bb="58"/>
        <link type="call" cfg="411" bb="8111"/>
      </succ>
    </bb>
    <bb id="58">
      <inst addr="0x83e0" instr="adds r3, r0, #1"/>
      <inst addr="0x83e2" instr="bne.n 83ea _i18n_number_rewrite+0x76"/>
      <succ>
        <link type="taken" cfg="3" bb="60"/>
        <link type="nottaken" cfg="3" bb="59"/>
      </succ>
    </bb>
    <bb id="59">
      <inst addr="0x83e4" instr="movs r3, #44 ; 0x2c"/>
      <inst addr="0x83e6" instr="strh r3, [r7, #20]"/>
      <inst addr="0x83e8" instr="b.n 83f6 _i18n_number_rewrite+0x82"/>
      <succ>
        <link type="taken" cfg="3" bb="61"/>
      </succ>
    </bb>
    <bb id="60">
      <inst addr="0x83ea" instr="add.w r3, r7, #48 ; 0x30"/>
      <inst addr="0x83ee" instr="adds r0, r3, r0"/>
      <inst addr="0x83f0" instr="movs r3, #0"/>
      <inst addr="0x83f2" instr="strb.w r3, [r0, #-28]"/>
      <succ>
        <link type="nottaken" cfg="3" bb="61"/>
      </succ>
    </bb>
    <bb id="61">
      <inst addr="0x83f6" instr="rsb r8, r4, r8"/>
      <inst addr="0x83fa" instr="cmp.w r8, #4096 ; 0x1000"/>
      <inst addr="0x83fe" instr="bls.n 840e _i18n_number_rewrite+0x9a"/>
      <succ>
        <link type="taken" cfg="3" bb="64"/>
        <link type="nottaken" cfg="3" bb="62"/>
      </succ>
    </bb>
    <bb id="62">
      <inst addr="0x8400" instr="mov r0, r8"/>
      <inst addr="0x8402" instr="bl 11b50 __libc_alloca_cutoff"/>
      <succ>
        <link type="nottaken" cfg="3" bb="63"/>
        <link type="call" cfg="197" bb="3335"/>
      </succ>
    </bb>
    <bb id="63">
      <inst addr="0x8406" instr="adds r0, #0"/>
      <inst addr="0x8408" instr="it ne"/>
      <inst addr="0x840a" instr="movne r0, #1"/>
      <inst addr="0x840c" instr="b.n 8410 _i18n_number_rewrite+0x9c"/>
      <succ>
        <link type="taken" cfg="3" bb="65"/>
      </succ>
    </bb>
    <bb id="64">
      <inst addr="0x840e" instr="movs r0, #1"/>
      <succ>
        <link type="nottaken" cfg="3" bb="65"/>
      </succ>
    </bb>
    <bb id="65">
      <inst addr="0x8410" instr="uxtb.w sl, r0"/>
      <inst addr="0x8414" instr="cmp.w sl, #0"/>
      <inst addr="0x8418" instr="beq.n 842a _i18n_number_rewrite+0xb6"/>
      <succ>
        <link type="taken" cfg="3" bb="67"/>
        <link type="nottaken" cfg="3" bb="66"/>
      </succ>
    </bb>
    <bb id="66">
      <inst addr="0x841a" instr="add.w r3, r8, #14"/>
      <inst addr="0x841e" instr="bic.w r3, r3, #7"/>
      <inst addr="0x8422" instr="sub.w sp, sp, r3"/>
      <inst addr="0x8426" instr="mov r9, sp"/>
      <inst addr="0x8428" instr="b.n 8436 _i18n_number_rewrite+0xc2"/>
      <succ>
        <link type="taken" cfg="3" bb="69"/>
      </succ>
    </bb>
    <bb id="67">
      <inst addr="0x842a" instr="mov r0, r8"/>
      <inst addr="0x842c" instr="bl e7f8 __libc_malloc"/>
      <succ>
        <link type="nottaken" cfg="3" bb="68"/>
        <link type="call" cfg="130" bb="2162"/>
      </succ>
    </bb>
    <bb id="68">
      <inst addr="0x8430" instr="mov r9, r0"/>
      <inst addr="0x8432" instr="cmp r0, #0"/>
      <inst addr="0x8434" instr="beq.n 84c2 _i18n_number_rewrite+0x14e"/>
      <succ>
        <link type="taken" cfg="3" bb="84"/>
        <link type="nottaken" cfg="3" bb="69"/>
      </succ>
    </bb>
    <bb id="69">
      <inst addr="0x8436" instr="mov r1, r4"/>
      <inst addr="0x8438" instr="mov r2, r8"/>
      <inst addr="0x843a" instr="mov r0, r9"/>
      <inst addr="0x843c" instr="mov r4, r6"/>
      <inst addr="0x843e" instr="bl 104b0 __mempcpy"/>
      <succ>
        <link type="nottaken" cfg="3" bb="70"/>
        <link type="call" cfg="156" bb="2878"/>
      </succ>
    </bb>
    <bb id="70">
      <inst addr="0x8442" instr="mrc 15, 0, fp, cr13, cr0, {3}"/>
      <inst addr="0x8446" instr="mov r8, r0"/>
      <inst addr="0x8448" instr="b.n 84ae _i18n_number_rewrite+0x13a"/>
      <succ>
        <link type="taken" cfg="3" bb="82"/>
      </succ>
    </bb>
    <bb id="82">
      <inst addr="0x84ae" instr="add.w r8, r8, #4294967295 ; 0xffffffff"/>
      <inst addr="0x84b2" instr="cmp r8, r9"/>
      <inst addr="0x84b4" instr="bcs.n 844a _i18n_number_rewrite+0xd6"/>
      <inst addr="0x84b6" instr="cmp.w sl, #0"/>
      <inst addr="0x84ba" instr="bne.n 84c2 _i18n_number_rewrite+0x14e"/>
      <succ>
        <link type="taken" cfg="3" bb="84"/>
        <link type="nottaken" cfg="3" bb="83"/>
      </succ>
    </bb>
    <bb id="83">
      <inst addr="0x84bc" instr="mov r0, r9"/>
      <inst addr="0x84be" instr="bl ec9c __cfree"/>
      <succ>
        <link type="nottaken" cfg="3" bb="84"/>
        <link type="call" cfg="134" bb="2289"/>
      </succ>
    </bb>
    <bb id="84">
      <inst addr="0x84c2" instr="mov r0, r4"/>
      <inst addr="0x84c4" instr="add.w r7, r7, #52 ; 0x34"/>
      <inst addr="0x84c8" instr="mov sp, r7"/>
      <inst addr="0x84ca" instr="ldmia.w sp!, {r4, r5, r6, r7, r8, r9, sl, fp, pc}"/>
      <inst addr="0x84ce" instr="nop"/>
      <inst addr="0x84d0" instr=".word 0x0004dce0"/>
      <inst addr="0x84d4" instr=".word 0x00061be0"/>
      <succ>
      </succ>
    </bb>
  </cfg>
  <cfg id="7" name="group_number_7">
    <bb id="148">
      <inst addr="0x8700" instr="stmdb sp!, {r3, r4, r5, r6, r7, r8, r9, lr}"/>
      <inst addr="0x8704" instr="mov r9, r3"/>
      <inst addr="0x8706" instr="ldrb r5, [r2, #0]"/>
      <inst addr="0x8708" instr="add r7, sp, #0"/>
      <inst addr="0x870a" instr="mov r4, r1"/>
      <inst addr="0x870c" instr="subs r3, r5, #1"/>
      <inst addr="0x870e" instr="uxtb r3, r3"/>
      <inst addr="0x8710" instr="cmp r3, #253 ; 0xfd"/>
      <inst addr="0x8712" instr="bhi.n 8784 group_number+0x84"/>
      <succ>
        <link type="taken" cfg="7" bb="159"/>
        <link type="nottaken" cfg="7" bb="149"/>
      </succ>
    </bb>
    <bb id="149">
      <inst addr="0x8714" instr="subs r3, r1, r0"/>
      <inst addr="0x8716" instr="mov r1, r0"/>
      <inst addr="0x8718" instr="bic.w r0, r3, #3"/>
      <inst addr="0x871c" instr="add.w r8, r2, #1"/>
      <inst addr="0x8720" instr="add.w r3, r0, #14"/>
      <inst addr="0x8724" instr="bic.w r3, r3, #7"/>
      <inst addr="0x8728" instr="mov r2, r0"/>
      <inst addr="0x872a" instr="sub.w sp, sp, r3"/>
      <inst addr="0x872e" instr="mov r0, sp"/>
      <inst addr="0x8730" instr="mov r6, sp"/>
      <inst addr="0x8732" instr="bl 104b0 __mempcpy"/>
      <succ>
        <link type="nottaken" cfg="7" bb="150"/>
        <link type="call" cfg="156" bb="2878"/>
      </succ>
    </bb>
    <bb id="150">
      <inst addr="0x8736" instr="mov r3, r0"/>
      <inst addr="0x8738" instr="mov r0, r4"/>
      <inst addr="0x873a" instr="b.n 877c group_number+0x7c"/>
      <succ>
        <link type="taken" cfg="7" bb="158"/>
      </succ>
    </bb>
    <bb id="151">
      <inst addr="0x873c" instr="ldr.w r1, [r3, #-4]!"/>
      <inst addr="0x8740" instr="subs r5, #1"/>
      <inst addr="0x8742" instr="str.w r1, [r0, #-4]"/>
      <inst addr="0x8746" instr="bne.n 877a group_number+0x7a"/>
      <succ>
        <link type="taken" cfg="7" bb="157"/>
        <link type="nottaken" cfg="7" bb="152"/>
      </succ>
    </bb>
    <bb id="152">
      <inst addr="0x8748" instr="cmp r3, r6"/>
      <inst addr="0x874a" instr="bls.n 877a group_number+0x7a"/>
      <succ>
        <link type="taken" cfg="7" bb="157"/>
        <link type="nottaken" cfg="7" bb="153"/>
      </succ>
    </bb>
    <bb id="153">
      <inst addr="0x874c" instr="str.w r9, [r0, #-8]"/>
      <inst addr="0x8750" instr="sub.w r2, r0, #8"/>
      <inst addr="0x8754" instr="ldrb.w r1, [r8]"/>
      <inst addr="0x8758" instr="cmp r1, #255 ; 0xff"/>
      <inst addr="0x875a" instr="mov r5, r1"/>
      <inst addr="0x875c" instr="bne.n 876e group_number+0x6e"/>
      <succ>
        <link type="taken" cfg="7" bb="155"/>
        <link type="nottaken" cfg="7" bb="154"/>
      </succ>
    </bb>
    <bb id="154">
      <inst addr="0x875e" instr="mov r0, r2"/>
      <inst addr="0x8760" instr="ldr.w r2, [r3, #-4]!"/>
      <inst addr="0x8764" instr="cmp r6, r3"/>
      <inst addr="0x8766" instr="str.w r2, [r0, #-4]!"/>
      <inst addr="0x876a" instr="bcc.n 8760 group_number+0x60"/>
      <inst addr="0x876c" instr="b.n 8784 group_number+0x84"/>
      <succ>
        <link type="taken" cfg="7" bb="159"/>
      </succ>
    </bb>
    <bb id="155">
      <inst addr="0x876e" instr="cbz r1, 8776 group_number+0x76"/>
      <inst addr="0x8770" instr="add.w r8, r8, #1"/>
      <inst addr="0x8774" instr="b.n 877a group_number+0x7a"/>
      <succ>
        <link type="taken" cfg="7" bb="157"/>
      </succ>
    </bb>
    <bb id="157">
      <inst addr="0x877a" instr="mov r0, r2"/>
      <succ>
        <link type="nottaken" cfg="7" bb="158"/>
      </succ>
    </bb>
    <bb id="158">
      <inst addr="0x877c" instr="cmp r3, r6"/>
      <inst addr="0x877e" instr="sub.w r2, r0, #4"/>
      <inst addr="0x8782" instr="bhi.n 873c group_number+0x3c"/>
      <succ>
        <link type="taken" cfg="7" bb="151"/>
        <link type="nottaken" cfg="7" bb="159"/>
      </succ>
    </bb>
    <bb id="159">
      <inst addr="0x8784" instr="mov sp, r7"/>
      <inst addr="0x8786" instr="ldmia.w sp!, {r3, r4, r5, r6, r7, r8, r9, pc}"/>
      <inst addr="0x878a" instr="nop"/>
      <succ>
      </succ>
    </bb>
  </cfg>
  <cfg id="8" name="_i18n_number_rewrite_8">
    <bb id="160">
      <inst addr="0x878c" instr="stmdb sp!, {r4, r5, r6, r7, r8, r9, sl, fp, lr}"/>
      <inst addr="0x8790" instr="sub sp, #12"/>
      <inst addr="0x8792" instr="mov r4, r0"/>
      <inst addr="0x8794" instr="add r7, sp, #0"/>
      <inst addr="0x8796" instr="ldr r0, [pc, #212] ; (886c _i18n_number_rewrite+0xe0)"/>
      <inst addr="0x8798" instr="mov r9, r2"/>
      <inst addr="0x879a" instr="mov r5, r1"/>
      <inst addr="0x879c" instr="bl 273f0 __wctrans"/>
      <succ>
        <link type="nottaken" cfg="8" bb="161"/>
        <link type="call" cfg="491" bb="9610"/>
      </succ>
    </bb>
    <bb id="161">
      <inst addr="0x87a0" instr="mov r1, r0"/>
      <inst addr="0x87a2" instr="mov r6, r0"/>
      <inst addr="0x87a4" instr="movs r0, #46 ; 0x2e"/>
      <inst addr="0x87a6" instr="bl 27440 __towctrans"/>
      <succ>
        <link type="nottaken" cfg="8" bb="162"/>
        <link type="call" cfg="492" bb="9616"/>
      </succ>
    </bb>
    <bb id="162">
      <inst addr="0x87aa" instr="mov r1, r6"/>
      <inst addr="0x87ac" instr="mov fp, r0"/>
      <inst addr="0x87ae" instr="movs r0, #44 ; 0x2c"/>
      <inst addr="0x87b0" instr="bl 27440 __towctrans"/>
      <succ>
        <link type="nottaken" cfg="8" bb="163"/>
        <link type="call" cfg="492" bb="9616"/>
      </succ>
    </bb>
    <bb id="163">
      <inst addr="0x87b4" instr="subs r2, r5, r4"/>
      <inst addr="0x87b6" instr="bic.w r2, r2, #3"/>
      <inst addr="0x87ba" instr="cmp.w r2, #4096 ; 0x1000"/>
      <inst addr="0x87be" instr="mov sl, r0"/>
      <inst addr="0x87c0" instr="bls.n 87d8 _i18n_number_rewrite+0x4c"/>
      <succ>
        <link type="taken" cfg="8" bb="166"/>
        <link type="nottaken" cfg="8" bb="164"/>
      </succ>
    </bb>
    <bb id="164">
      <inst addr="0x87c2" instr="mov r0, r2"/>
      <inst addr="0x87c4" instr="str r2, [r7, #4]"/>
      <inst addr="0x87c6" instr="bl 11b50 __libc_alloca_cutoff"/>
      <succ>
        <link type="nottaken" cfg="8" bb="165"/>
        <link type="call" cfg="197" bb="3335"/>
      </succ>
    </bb>
    <bb id="165">
      <inst addr="0x87ca" instr="ldr r2, [r7, #4]"/>
      <inst addr="0x87cc" instr="adds.w r8, r0, #0"/>
      <inst addr="0x87d0" instr="it ne"/>
      <inst addr="0x87d2" instr="movne.w r8, #1"/>
      <inst addr="0x87d6" instr="b.n 87dc _i18n_number_rewrite+0x50"/>
      <succ>
        <link type="taken" cfg="8" bb="167"/>
      </succ>
    </bb>
    <bb id="166">
      <inst addr="0x87d8" instr="mov.w r8, #1"/>
      <succ>
        <link type="nottaken" cfg="8" bb="167"/>
      </succ>
    </bb>
    <bb id="167">
      <inst addr="0x87dc" instr="uxtb.w r8, r8"/>
      <inst addr="0x87e0" instr="cmp.w r8, #0"/>
      <inst addr="0x87e4" instr="beq.n 87f6 _i18n_number_rewrite+0x6a"/>
      <succ>
        <link type="taken" cfg="8" bb="169"/>
        <link type="nottaken" cfg="8" bb="168"/>
      </succ>
    </bb>
    <bb id="168">
      <inst addr="0x87e6" instr="add.w r3, r2, #14"/>
      <inst addr="0x87ea" instr="bic.w r3, r3, #7"/>
      <inst addr="0x87ee" instr="sub.w sp, sp, r3"/>
      <inst addr="0x87f2" instr="mov r5, sp"/>
      <inst addr="0x87f4" instr="b.n 8804 _i18n_number_rewrite+0x78"/>
      <succ>
        <link type="taken" cfg="8" bb="171"/>
      </succ>
    </bb>
    <bb id="169">
      <inst addr="0x87f6" instr="mov r0, r2"/>
      <inst addr="0x87f8" instr="str r2, [r7, #4]"/>