<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program [
<!ATTLIST program
   name CDATA #IMPLIED>
<!ELEMENT program (cfg*)>
<!ATTLIST cfg
  id ID #REQUIRED
  main CDATA #IMPLIED
  name CDATA #IMPLIED>
<!ELEMENT cfg (bb+)>
<!ATTLIST bb
   id ID #REQUIRED>
<!ELEMENT bb (prec?,inst*,succ?)>
<!ELEMENT prec (link+)>
<!ELEMENT succ (link+)>
<!ATTLIST link
  type (taken|nottaken|call) #REQUIRED
  cfg CDATA #REQUIRED
  bb IDREF #REQUIRED>
<!ELEMENT link EMPTY>
<!ATTLIST inst
   addr CDATA #REQUIRED
   instr CDATA #IMPLIED>
<!ELEMENT inst EMPTY>
]>
<program name="newtonMethod">
  <cfg id="5" name="maxDoub">
    <bb id="6">
      <inst addr="0x81e0" instr="{r7}"/>
      <inst addr="0x81e2" instr="sub sp, #20"/>
      <inst addr="0x81e4" instr="add r7, sp, #0"/>
      <inst addr="0x81e6" instr="strd r0, r1, [r7, #8]"/>
      <inst addr="0x81ea" instr="strd r2, r3, [r7]"/>
      <inst addr="0x81ee" instr="vldr d6, [r7, #8]"/>
      <inst addr="0x81f2" instr="vldr d7, [r7]"/>
      <inst addr="0x81f6" instr="vcmpe.f64 d6, d7"/>
      <inst addr="0x81fa" instr="vmrs APSR_nzcv, fpscr"/>
      <inst addr="0x81fe" instr="ite le"/>
      <inst addr="0x8200" instr="movle r3, #0"/>
      <inst addr="0x8202" instr="movgt r3, #1"/>
      <inst addr="0x8204" instr="r3, r3"/>
      <inst addr="0x8206" instr="cmp r3, #0"/>
      <inst addr="0x8208" instr="beq.n 8210 maxDoub+0x30"/>
      <succ>
        <link type="taken" cfg="5" bb="8"/>
        <link type="nottaken" cfg="5" bb="7"/>
      </succ>
    </bb>
    <bb id="7">
      <inst addr="0x820a" instr="vldr d7, [r7, #8]"/>
      <inst addr="0x820e" instr="b.n 8214 maxDoub+0x34"/>
      <succ>
        <link type="taken" cfg="5" bb="9"/>
      </succ>
    </bb>
    <bb id="8">
      <inst addr="0x8210" instr="vldr d7, [r7]"/>
      <succ>
        <link type="nottaken" cfg="5" bb="9"/>
      </succ>
    </bb>
    <bb id="9">
      <inst addr="0x8214" instr="vmov r2, r3, d7"/>
      <inst addr="0x8218" instr="mov r0, r2"/>
      <inst addr="0x821a" instr="mov r1, r3"/>
      <inst addr="0x821c" instr="add.w r7, r7, #20"/>
      <inst addr="0x8220" instr="mov sp, r7"/>
      <inst addr="0x8222" instr="pop {r7}"/>
      <inst addr="0x8224" instr="bx lr"/>
      <inst addr="0x8226" instr="nop"/>
      <succ>
      </succ>
    </bb>
  </cfg>
  <cfg id="6" name="initialiseLUdcmp">
    <bb id="10">
      <inst addr="0x8228" instr="{r4, r7, lr}"/>
      <inst addr="0x822a" instr="sub sp, #180 ; 0xb4"/>
      <inst addr="0x822c" instr="add r7, sp, #0"/>
      <inst addr="0x822e" instr="mov r4, r0"/>
      <inst addr="0x8230" instr="str r1, [r7, #4]"/>
      <inst addr="0x8232" instr="mov.w r3, #3"/>
      <inst addr="0x8236" instr="str r3, [r7, #32]"/>
      <inst addr="0x8238" instr="mov.w r3, #0"/>
      <inst addr="0x823c" instr="str.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x8240" instr="b.n 82b8 initialiseLUdcmp+0x90"/>
      <succ>
        <link type="taken" cfg="6" bb="15"/>
      </succ>
    </bb>
    <bb id="11">
      <inst addr="0x8242" instr="mov.w r3, #0"/>
      <inst addr="0x8246" instr="str.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x824a" instr="b.n 82a4 initialiseLUdcmp+0x7c"/>
      <succ>
        <link type="taken" cfg="6" bb="13"/>
      </succ>
    </bb>
    <bb id="12">
      <inst addr="0x824c" instr="ldr.w r2, [r7, #136] ; 0x88"/>
      <inst addr="0x8250" instr="ldr.w r0, [r7, #140] ; 0x8c"/>
      <inst addr="0x8254" instr="ldr.w r1, [r7, #136] ; 0x88"/>
      <inst addr="0x8258" instr="mov r3, r1"/>
      <inst addr="0x825a" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x825e" instr="add r3, r1"/>
      <inst addr="0x8260" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x8264" instr="mov r1, r3"/>
      <inst addr="0x8266" instr="ldr r3, [r7, #4]"/>
      <inst addr="0x8268" instr="add r3, r1"/>
      <inst addr="0x826a" instr="ldr.w r1, [r7, #140] ; 0x8c"/>
      <inst addr="0x826e" instr="mov.w r1, r1, lsl #3"/>
      <inst addr="0x8272" instr="add r3, r1"/>
      <inst addr="0x8274" instr="vldr d7, [r3]"/>
      <inst addr="0x8278" instr="mov r3, r2"/>
      <inst addr="0x827a" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x827e" instr="add r3, r2"/>
      <inst addr="0x8280" instr="add r3, r0"/>
      <inst addr="0x8282" instr="add.w r3, r3, #1"/>
      <inst addr="0x8286" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x828a" instr="add.w r0, r7, #176 ; 0xb0"/>
      <inst addr="0x828e" instr="add r3, r0"/>
      <inst addr="0x8290" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x8294" instr="vstr d7, [r3]"/>
      <inst addr="0x8298" instr="ldr.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x829c" instr="add.w r3, r3, #1"/>
      <inst addr="0x82a0" instr="str.w r3, [r7, #140] ; 0x8c"/>
      <succ>
        <link type="nottaken" cfg="6" bb="13"/>
      </succ>
    </bb>
    <bb id="13">
      <inst addr="0x82a4" instr="ldr.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x82a8" instr="cmp r3, #2"/>
      <inst addr="0x82aa" instr="ble.n 824c initialiseLUdcmp+0x24"/>
      <succ>
        <link type="taken" cfg="6" bb="12"/>
        <link type="nottaken" cfg="6" bb="14"/>
      </succ>
    </bb>
    <bb id="14">
      <inst addr="0x82ac" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x82b0" instr="add.w r3, r3, #1"/>
      <inst addr="0x82b4" instr="str.w r3, [r7, #136] ; 0x88"/>
      <succ>
        <link type="nottaken" cfg="6" bb="15"/>
      </succ>
    </bb>
    <bb id="15">
      <inst addr="0x82b8" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x82bc" instr="cmp r3, #2"/>
      <inst addr="0x82be" instr="ble.n 8242 initialiseLUdcmp+0x1a"/>
      <succ>
        <link type="taken" cfg="6" bb="11"/>
        <link type="nottaken" cfg="6" bb="16"/>
      </succ>
    </bb>
    <bb id="16">
      <inst addr="0x82c0" instr="vldr d7, [pc, #796] ; 85e0 initialiseLUdcmp+0x3b8"/>
      <inst addr="0x82c4" instr="vstr d7, [r7, #144] ; 0x90"/>
      <inst addr="0x82c8" instr="vmov.f64 d7, #112 ; 0x70"/>
      <inst addr="0x82cc" instr="vstr d7, [r7, #128] ; 0x80"/>
      <inst addr="0x82d0" instr="mov.w r3, #0"/>
      <inst addr="0x82d4" instr="str.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x82d8" instr="b.n 839a initialiseLUdcmp+0x172"/>
      <succ>
        <link type="taken" cfg="6" bb="25"/>
      </succ>
    </bb>
    <bb id="17">
      <inst addr="0x82da" instr="vldr d7, [pc, #780] ; 85ea initialiseLUdcmp+0x3c2"/>
      <inst addr="0x82de" instr="vstr d7, [r7, #160] ; 0xa0"/>
      <inst addr="0x82e2" instr="mov.w r3, #0"/>
      <inst addr="0x82e6" instr="str.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x82ea" instr="b.n 834c initialiseLUdcmp+0x124"/>
      <succ>
        <link type="taken" cfg="6" bb="21"/>
      </succ>
    </bb>
    <bb id="18">
      <inst addr="0x82ec" instr="ldr.w r2, [r7, #136] ; 0x88"/>
      <inst addr="0x82f0" instr="ldr.w r1, [r7, #140] ; 0x8c"/>
      <inst addr="0x82f4" instr="mov r3, r2"/>
      <inst addr="0x82f6" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x82fa" instr="add r3, r2"/>
      <inst addr="0x82fc" instr="add r3, r1"/>
      <inst addr="0x82fe" instr="add.w r3, r3, #1"/>
      <inst addr="0x8302" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x8306" instr="add.w r1, r7, #176 ; 0xb0"/>
      <inst addr="0x830a" instr="add r3, r1"/>
      <inst addr="0x830c" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x8310" instr="vldr d7, [r3]"/>
      <inst addr="0x8314" instr="vabs.f64 d7, d7"/>
      <inst addr="0x8318" instr="vstr d7, [r7, #168] ; 0xa8"/>
      <inst addr="0x831c" instr="vldr d6, [r7, #168] ; 0xa8"/>
      <inst addr="0x8320" instr="vldr d7, [r7, #160] ; 0xa0"/>
      <inst addr="0x8324" instr="vcmpe.f64 d6, d7"/>
      <inst addr="0x8328" instr="vmrs APSR_nzcv, fpscr"/>
      <inst addr="0x832c" instr="ite le"/>
      <inst addr="0x832e" instr="movle r3, #0"/>
      <inst addr="0x8330" instr="movgt r3, #1"/>
      <inst addr="0x8332" instr="r3, r3"/>
      <inst addr="0x8334" instr="cmp r3, #0"/>
      <inst addr="0x8336" instr="beq.n 8340 initialiseLUdcmp+0x118"/>
      <succ>
        <link type="taken" cfg="6" bb="20"/>
        <link type="nottaken" cfg="6" bb="19"/>
      </succ>
    </bb>
    <bb id="19">
      <inst addr="0x8338" instr="vldr d7, [r7, #168] ; 0xa8"/>
      <inst addr="0x833c" instr="vstr d7, [r7, #160] ; 0xa0"/>
      <succ>
        <link type="nottaken" cfg="6" bb="20"/>
      </succ>
    </bb>
    <bb id="20">
      <inst addr="0x8340" instr="ldr.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x8344" instr="add.w r3, r3, #1"/>
      <inst addr="0x8348" instr="str.w r3, [r7, #140] ; 0x8c"/>
      <succ>
        <link type="nottaken" cfg="6" bb="21"/>
      </succ>
    </bb>
    <bb id="21">
      <inst addr="0x834c" instr="ldr r2, [r7, #32]"/>
      <inst addr="0x834e" instr="ldr.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x8352" instr="cmp r2, r3"/>
      <inst addr="0x8354" instr="bgt.n 82ec initialiseLUdcmp+0xc4"/>
      <succ>
        <link type="taken" cfg="6" bb="18"/>
        <link type="nottaken" cfg="6" bb="22"/>
      </succ>
    </bb>
    <bb id="22">
      <inst addr="0x8356" instr="vldr d7, [r7, #160] ; 0xa0"/>
      <inst addr="0x835a" instr="vcmp.f64 d7, #0.0"/>
      <inst addr="0x835e" instr="vmrs APSR_nzcv, fpscr"/>
      <inst addr="0x8362" instr="bne.n 836c initialiseLUdcmp+0x144"/>
      <succ>
        <link type="taken" cfg="6" bb="24"/>
        <link type="nottaken" cfg="6" bb="23"/>
      </succ>
    </bb>
    <bb id="23">
      <inst addr="0x8364" instr="mov.w r0, #1"/>
      <inst addr="0x8368" instr="blx 13504 exit"/>
      <succ>
        <link type="nottaken" cfg="6" bb="24"/>
      </succ>
    </bb>
    <bb id="24">
      <inst addr="0x836c" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x8370" instr="vmov.f64 d6, #112 ; 0x70"/>
      <inst addr="0x8374" instr="vldr d7, [r7, #160] ; 0xa0"/>
      <inst addr="0x8378" instr="vdiv.f64 d7, d6, d7"/>
      <inst addr="0x837c" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x8380" instr="add.w r2, r7, #176 ; 0xb0"/>
      <inst addr="0x8384" instr="add r3, r2"/>
      <inst addr="0x8386" instr="sub.w r3, r3, #168 ; 0xa8"/>
      <inst addr="0x838a" instr="vstr d7, [r3]"/>
      <inst addr="0x838e" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x8392" instr="add.w r3, r3, #1"/>
      <inst addr="0x8396" instr="str.w r3, [r7, #136] ; 0x88"/>
      <succ>
        <link type="nottaken" cfg="6" bb="25"/>
      </succ>
    </bb>
    <bb id="25">
      <inst addr="0x839a" instr="ldr r2, [r7, #32]"/>
      <inst addr="0x839c" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x83a0" instr="cmp r2, r3"/>
      <inst addr="0x83a2" instr="bgt.n 82da initialiseLUdcmp+0xb2"/>
      <succ>
        <link type="taken" cfg="6" bb="17"/>
        <link type="nottaken" cfg="6" bb="26"/>
      </succ>
    </bb>
    <bb id="26">
      <inst addr="0x83a4" instr="mov.w r3, #0"/>
      <inst addr="0x83a8" instr="str.w r3, [r7, #156] ; 0x9c"/>
      <inst addr="0x83ac" instr="b.n 875c initialiseLUdcmp+0x534"/>
      <succ>
        <link type="taken" cfg="6" bb="47"/>
      </succ>
    </bb>
    <bb id="27">
      <inst addr="0x83ae" instr="vldr d7, [pc, #568] ; 85ea initialiseLUdcmp+0x3c2"/>
      <inst addr="0x83b2" instr="vstr d7, [r7, #160] ; 0xa0"/>
      <inst addr="0x83b6" instr="ldr.w r3, [r7, #156] ; 0x9c"/>
      <inst addr="0x83ba" instr="str.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x83be" instr="b.n 8442 initialiseLUdcmp+0x21a"/>
      <succ>
        <link type="taken" cfg="6" bb="31"/>
      </succ>
    </bb>
    <bb id="28">
      <inst addr="0x83c0" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x83c4" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x83c8" instr="add.w r0, r7, #176 ; 0xb0"/>
      <inst addr="0x83cc" instr="add r3, r0"/>
      <inst addr="0x83ce" instr="sub.w r3, r3, #168 ; 0xa8"/>
      <inst addr="0x83d2" instr="vldr d6, [r3]"/>
      <inst addr="0x83d6" instr="ldr.w r2, [r7, #136] ; 0x88"/>
      <inst addr="0x83da" instr="ldr.w r1, [r7, #156] ; 0x9c"/>
      <inst addr="0x83de" instr="mov r3, r2"/>
      <inst addr="0x83e0" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x83e4" instr="add r3, r2"/>
      <inst addr="0x83e6" instr="add r3, r1"/>
      <inst addr="0x83e8" instr="add.w r3, r3, #1"/>
      <inst addr="0x83ec" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x83f0" instr="add.w r1, r7, #176 ; 0xb0"/>
      <inst addr="0x83f4" instr="add r3, r1"/>
      <inst addr="0x83f6" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x83fa" instr="vldr d7, [r3]"/>
      <inst addr="0x83fe" instr="vabs.f64 d7, d7"/>
      <inst addr="0x8402" instr="vmul.f64 d7, d6, d7"/>
      <inst addr="0x8406" instr="vstr d7, [r7, #168] ; 0xa8"/>
      <inst addr="0x840a" instr="vldr d6, [r7, #168] ; 0xa8"/>
      <inst addr="0x840e" instr="vldr d7, [r7, #160] ; 0xa0"/>
      <inst addr="0x8412" instr="vcmpe.f64 d6, d7"/>
      <inst addr="0x8416" instr="vmrs APSR_nzcv, fpscr"/>
      <inst addr="0x841a" instr="ite le"/>
      <inst addr="0x841c" instr="movle r3, #0"/>
      <inst addr="0x841e" instr="movgt r3, #1"/>
      <inst addr="0x8420" instr="r3, r3"/>
      <inst addr="0x8422" instr="cmp r3, #0"/>
      <inst addr="0x8424" instr="beq.n 8436 initialiseLUdcmp+0x20e"/>
      <succ>
        <link type="taken" cfg="6" bb="30"/>
        <link type="nottaken" cfg="6" bb="29"/>
      </succ>
    </bb>
    <bb id="29">
      <inst addr="0x8426" instr="vldr d7, [r7, #168] ; 0xa8"/>
      <inst addr="0x842a" instr="vstr d7, [r7, #160] ; 0xa0"/>
      <inst addr="0x842e" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x8432" instr="str.w r3, [r7, #152] ; 0x98"/>
      <succ>
        <link type="nottaken" cfg="6" bb="30"/>
      </succ>
    </bb>
    <bb id="30">
      <inst addr="0x8436" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x843a" instr="add.w r3, r3, #1"/>
      <inst addr="0x843e" instr="str.w r3, [r7, #136] ; 0x88"/>
      <succ>
        <link type="nottaken" cfg="6" bb="31"/>
      </succ>
    </bb>
    <bb id="31">
      <inst addr="0x8442" instr="ldr r2, [r7, #32]"/>
      <inst addr="0x8444" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x8448" instr="cmp r2, r3"/>
      <inst addr="0x844a" instr="bgt.n 83c0 initialiseLUdcmp+0x198"/>
      <succ>
        <link type="taken" cfg="6" bb="28"/>
        <link type="nottaken" cfg="6" bb="32"/>
      </succ>
    </bb>
    <bb id="32">
      <inst addr="0x844c" instr="ldr.w r2, [r7, #156] ; 0x9c"/>
      <inst addr="0x8450" instr="ldr.w r3, [r7, #152] ; 0x98"/>
      <inst addr="0x8454" instr="cmp r2, r3"/>
      <inst addr="0x8456" instr="beq.n 8558 initialiseLUdcmp+0x330"/>
      <succ>
        <link type="taken" cfg="6" bb="37"/>
        <link type="nottaken" cfg="6" bb="33"/>
      </succ>
    </bb>
    <bb id="33">
      <inst addr="0x8458" instr="mov.w r3, #0"/>
      <inst addr="0x845c" instr="str.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x8460" instr="b.n 8516 initialiseLUdcmp+0x2ee"/>
      <succ>
        <link type="taken" cfg="6" bb="35"/>
      </succ>
    </bb>
    <bb id="34">
      <inst addr="0x8462" instr="ldr.w r2, [r7, #152] ; 0x98"/>
      <inst addr="0x8466" instr="ldr.w r1, [r7, #140] ; 0x8c"/>
      <inst addr="0x846a" instr="mov r3, r2"/>
      <inst addr="0x846c" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x8470" instr="add r3, r2"/>
      <inst addr="0x8472" instr="add r3, r1"/>
      <inst addr="0x8474" instr="add.w r3, r3, #1"/>
      <inst addr="0x8478" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x847c" instr="add.w r2, r7, #176 ; 0xb0"/>
      <inst addr="0x8480" instr="add r3, r2"/>
      <inst addr="0x8482" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x8486" instr="vldr d7, [r3]"/>
      <inst addr="0x848a" instr="vstr d7, [r7, #168] ; 0xa8"/>
      <inst addr="0x848e" instr="ldr.w r2, [r7, #152] ; 0x98"/>
      <inst addr="0x8492" instr="ldr.w r0, [r7, #140] ; 0x8c"/>
      <inst addr="0x8496" instr="ldr.w r1, [r7, #156] ; 0x9c"/>
      <inst addr="0x849a" instr="ldr.w ip, [r7, #140] ; 0x8c"/>
      <inst addr="0x849e" instr="mov r3, r1"/>
      <inst addr="0x84a0" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x84a4" instr="add r3, r1"/>
      <inst addr="0x84a6" instr="add r3, ip"/>
      <inst addr="0x84a8" instr="add.w r3, r3, #1"/>
      <inst addr="0x84ac" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x84b0" instr="add.w r1, r7, #176 ; 0xb0"/>
      <inst addr="0x84b4" instr="add r3, r1"/>
      <inst addr="0x84b6" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x84ba" instr="vldr d7, [r3]"/>
      <inst addr="0x84be" instr="mov r3, r2"/>
      <inst addr="0x84c0" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x84c4" instr="add r3, r2"/>
      <inst addr="0x84c6" instr="add r3, r0"/>
      <inst addr="0x84c8" instr="add.w r3, r3, #1"/>
      <inst addr="0x84cc" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x84d0" instr="add.w r2, r7, #176 ; 0xb0"/>
      <inst addr="0x84d4" instr="add r3, r2"/>
      <inst addr="0x84d6" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x84da" instr="vstr d7, [r3]"/>
      <inst addr="0x84de" instr="ldr.w r2, [r7, #156] ; 0x9c"/>
      <inst addr="0x84e2" instr="ldr.w r1, [r7, #140] ; 0x8c"/>
      <inst addr="0x84e6" instr="mov r3, r2"/>
      <inst addr="0x84e8" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x84ec" instr="add r3, r2"/>
      <inst addr="0x84ee" instr="add r3, r1"/>
      <inst addr="0x84f0" instr="add.w r3, r3, #1"/>
      <inst addr="0x84f4" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x84f8" instr="add.w r0, r7, #176 ; 0xb0"/>
      <inst addr="0x84fc" instr="add r3, r0"/>
      <inst addr="0x84fe" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x8502" instr="vldr d7, [r7, #168] ; 0xa8"/>
      <inst addr="0x8506" instr="vstr d7, [r3]"/>
      <inst addr="0x850a" instr="ldr.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x850e" instr="add.w r3, r3, #1"/>
      <inst addr="0x8512" instr="str.w r3, [r7, #140] ; 0x8c"/>
      <succ>
        <link type="nottaken" cfg="6" bb="35"/>
      </succ>
    </bb>
    <bb id="35">
      <inst addr="0x8516" instr="ldr r2, [r7, #32]"/>
      <inst addr="0x8518" instr="ldr.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x851c" instr="cmp r2, r3"/>
      <inst addr="0x851e" instr="bgt.n 8462 initialiseLUdcmp+0x23a"/>
      <succ>
        <link type="taken" cfg="6" bb="34"/>
        <link type="nottaken" cfg="6" bb="36"/>
      </succ>
    </bb>
    <bb id="36">
      <inst addr="0x8520" instr="vldr d7, [r7, #128] ; 0x80"/>
      <inst addr="0x8524" instr="vneg.f64 d7, d7"/>
      <inst addr="0x8528" instr="vstr d7, [r7, #128] ; 0x80"/>
      <inst addr="0x852c" instr="ldr.w r3, [r7, #152] ; 0x98"/>
      <inst addr="0x8530" instr="ldr.w r2, [r7, #156] ; 0x9c"/>
      <inst addr="0x8534" instr="mov.w r2, r2, lsl #3"/>
      <inst addr="0x8538" instr="add.w r1, r7, #176 ; 0xb0"/>
      <inst addr="0x853c" instr="add r2, r1"/>
      <inst addr="0x853e" instr="sub.w r2, r2, #168 ; 0xa8"/>
      <inst addr="0x8542" instr="vldr d7, [r2]"/>
      <inst addr="0x8546" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x854a" instr="add.w r2, r7, #176 ; 0xb0"/>
      <inst addr="0x854e" instr="add r3, r2"/>
      <inst addr="0x8550" instr="sub.w r3, r3, #168 ; 0xa8"/>
      <inst addr="0x8554" instr="vstr d7, [r3]"/>
      <succ>
        <link type="nottaken" cfg="6" bb="37"/>
      </succ>
    </bb>
    <bb id="37">
      <inst addr="0x8558" instr="ldr.w r3, [r7, #156] ; 0x9c"/>
      <inst addr="0x855c" instr="add.w r3, r3, #20"/>
      <inst addr="0x8560" instr="mov.w r3, r3, lsl #2"/>
      <inst addr="0x8564" instr="add.w r0, r7, #176 ; 0xb0"/>
      <inst addr="0x8568" instr="add r3, r0"/>
      <inst addr="0x856a" instr="ldr.w r2, [r7, #152] ; 0x98"/>
      <inst addr="0x856e" instr="str.w r2, [r3, #-144]"/>
      <inst addr="0x8572" instr="ldr.w r2, [r7, #156] ; 0x9c"/>
      <inst addr="0x8576" instr="ldr.w r1, [r7, #156] ; 0x9c"/>
      <inst addr="0x857a" instr="mov r3, r2"/>
      <inst addr="0x857c" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x8580" instr="add r3, r2"/>
      <inst addr="0x8582" instr="add r3, r1"/>
      <inst addr="0x8584" instr="add.w r3, r3, #1"/>
      <inst addr="0x8588" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x858c" instr="add.w r1, r7, #176 ; 0xb0"/>
      <inst addr="0x8590" instr="add r3, r1"/>
      <inst addr="0x8592" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x8596" instr="vldr d7, [r3]"/>
      <inst addr="0x859a" instr="vcmp.f64 d7, #0.0"/>
      <inst addr="0x859e" instr="vmrs APSR_nzcv, fpscr"/>
      <inst addr="0x85a2" instr="bne.n 85d0 initialiseLUdcmp+0x3a8"/>
      <succ>
        <link type="taken" cfg="6" bb="39"/>
        <link type="nottaken" cfg="6" bb="38"/>
      </succ>
    </bb>
    <bb id="38">
      <inst addr="0x85a4" instr="ldr.w r2, [r7, #156] ; 0x9c"/>
      <inst addr="0x85a8" instr="ldr.w r1, [r7, #156] ; 0x9c"/>
      <inst addr="0x85ac" instr="mov r3, r2"/>
      <inst addr="0x85ae" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x85b2" instr="add r3, r2"/>
      <inst addr="0x85b4" instr="add r3, r1"/>
      <inst addr="0x85b6" instr="add.w r3, r3, #1"/>
      <inst addr="0x85ba" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x85be" instr="add.w r2, r7, #176 ; 0xb0"/>
      <inst addr="0x85c2" instr="add r3, r2"/>
      <inst addr="0x85c4" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x85c8" instr="vldr d7, [r7, #144] ; 0x90"/>
      <inst addr="0x85cc" instr="vstr d7, [r3]"/>
      <succ>
        <link type="nottaken" cfg="6" bb="39"/>
      </succ>
    </bb>
    <bb id="39">
      <inst addr="0x85d0" instr="ldr.w r3, [r7, #156] ; 0x9c"/>
      <inst addr="0x85d4" instr="add.w r3, r3, #1"/>
      <inst addr="0x85d8" instr="str.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x85dc" instr="b.n 8744 initialiseLUdcmp+0x51c"/>
      <succ>
        <link type="taken" cfg="6" bb="45"/>
      </succ>
    </bb>
    <bb id="41">
      <inst addr="0x85f0" instr="ldr.w r2, [r7, #136] ; 0x88"/>
      <inst addr="0x85f4" instr="ldr.w r1, [r7, #156] ; 0x9c"/>
      <inst addr="0x85f8" instr="ldr.w r0, [r7, #136] ; 0x88"/>
      <inst addr="0x85fc" instr="ldr.w ip, [r7, #156] ; 0x9c"/>
      <inst addr="0x8600" instr="mov r3, r0"/>
      <inst addr="0x8602" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x8606" instr="add r3, r0"/>
      <inst addr="0x8608" instr="add r3, ip"/>
      <inst addr="0x860a" instr="add.w r3, r3, #1"/>
      <inst addr="0x860e" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x8612" instr="add.w r0, r7, #176 ; 0xb0"/>
      <inst addr="0x8616" instr="add r3, r0"/>
      <inst addr="0x8618" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x861c" instr="vldr d6, [r3]"/>
      <inst addr="0x8620" instr="ldr.w r0, [r7, #156] ; 0x9c"/>
      <inst addr="0x8624" instr="ldr.w ip, [r7, #156] ; 0x9c"/>
      <inst addr="0x8628" instr="mov r3, r0"/>
      <inst addr="0x862a" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x862e" instr="add r3, r0"/>
      <inst addr="0x8630" instr="add r3, ip"/>
      <inst addr="0x8632" instr="add.w r3, r3, #1"/>
      <inst addr="0x8636" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x863a" instr="add.w r0, r7, #176 ; 0xb0"/>
      <inst addr="0x863e" instr="add r3, r0"/>
      <inst addr="0x8640" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x8644" instr="vldr d7, [r3]"/>
      <inst addr="0x8648" instr="vdiv.f64 d7, d6, d7"/>
      <inst addr="0x864c" instr="mov r3, r2"/>
      <inst addr="0x864e" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x8652" instr="add r3, r2"/>
      <inst addr="0x8654" instr="add r3, r1"/>
      <inst addr="0x8656" instr="add.w r3, r3, #1"/>
      <inst addr="0x865a" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x865e" instr="add.w r0, r7, #176 ; 0xb0"/>
      <inst addr="0x8662" instr="add r3, r0"/>
      <inst addr="0x8664" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x8668" instr="vstr d7, [r3]"/>
      <inst addr="0x866c" instr="mov r3, r2"/>
      <inst addr="0x866e" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x8672" instr="add r3, r2"/>
      <inst addr="0x8674" instr="add r3, r1"/>
      <inst addr="0x8676" instr="add.w r3, r3, #1"/>
      <inst addr="0x867a" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x867e" instr="add.w r1, r7, #176 ; 0xb0"/>
      <inst addr="0x8682" instr="add r3, r1"/>
      <inst addr="0x8684" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x8688" instr="vldr d7, [r3]"/>
      <inst addr="0x868c" instr="vstr d7, [r7, #168] ; 0xa8"/>
      <inst addr="0x8690" instr="ldr.w r3, [r7, #156] ; 0x9c"/>
      <inst addr="0x8694" instr="add.w r3, r3, #1"/>
      <inst addr="0x8698" instr="str.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x869c" instr="b.n 872e initialiseLUdcmp+0x506"/>
      <succ>
        <link type="taken" cfg="6" bb="43"/>
      </succ>
    </bb>
    <bb id="42">
      <inst addr="0x869e" instr="ldr.w r2, [r7, #136] ; 0x88"/>
      <inst addr="0x86a2" instr="ldr.w r0, [r7, #140] ; 0x8c"/>
      <inst addr="0x86a6" instr="ldr.w r1, [r7, #136] ; 0x88"/>
      <inst addr="0x86aa" instr="ldr.w ip, [r7, #140] ; 0x8c"/>
      <inst addr="0x86ae" instr="mov r3, r1"/>
      <inst addr="0x86b0" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x86b4" instr="add r3, r1"/>
      <inst addr="0x86b6" instr="add r3, ip"/>
      <inst addr="0x86b8" instr="add.w r3, r3, #1"/>
      <inst addr="0x86bc" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x86c0" instr="add.w r1, r7, #176 ; 0xb0"/>
      <inst addr="0x86c4" instr="add r3, r1"/>
      <inst addr="0x86c6" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x86ca" instr="vldr d6, [r3]"/>
      <inst addr="0x86ce" instr="ldr.w r1, [r7, #156] ; 0x9c"/>
      <inst addr="0x86d2" instr="ldr.w ip, [r7, #140] ; 0x8c"/>
      <inst addr="0x86d6" instr="mov r3, r1"/>
      <inst addr="0x86d8" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x86dc" instr="add r3, r1"/>
      <inst addr="0x86de" instr="add r3, ip"/>
      <inst addr="0x86e0" instr="add.w r3, r3, #1"/>
      <inst addr="0x86e4" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x86e8" instr="add.w r1, r7, #176 ; 0xb0"/>
      <inst addr="0x86ec" instr="add r3, r1"/>
      <inst addr="0x86ee" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x86f2" instr="vldr d5, [r3]"/>
      <inst addr="0x86f6" instr="vldr d7, [r7, #168] ; 0xa8"/>
      <inst addr="0x86fa" instr="vmul.f64 d7, d5, d7"/>
      <inst addr="0x86fe" instr="vsub.f64 d7, d6, d7"/>
      <inst addr="0x8702" instr="mov r3, r2"/>
      <inst addr="0x8704" instr="mov.w r3, r3, lsl #1"/>
      <inst addr="0x8708" instr="add r3, r2"/>
      <inst addr="0x870a" instr="add r3, r0"/>
      <inst addr="0x870c" instr="add.w r3, r3, #1"/>
      <inst addr="0x8710" instr="mov.w r3, r3, lsl #3"/>
      <inst addr="0x8714" instr="add.w r2, r7, #176 ; 0xb0"/>
      <inst addr="0x8718" instr="add r3, r2"/>
      <inst addr="0x871a" instr="sub.w r3, r3, #144 ; 0x90"/>
      <inst addr="0x871e" instr="vstr d7, [r3]"/>
      <inst addr="0x8722" instr="ldr.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x8726" instr="add.w r3, r3, #1"/>
      <inst addr="0x872a" instr="str.w r3, [r7, #140] ; 0x8c"/>
      <succ>
        <link type="nottaken" cfg="6" bb="43"/>
      </succ>
    </bb>
    <bb id="43">
      <inst addr="0x872e" instr="ldr r2, [r7, #32]"/>
      <inst addr="0x8730" instr="ldr.w r3, [r7, #140] ; 0x8c"/>
      <inst addr="0x8734" instr="cmp r2, r3"/>
      <inst addr="0x8736" instr="bgt.n 869e initialiseLUdcmp+0x476"/>
      <succ>
        <link type="taken" cfg="6" bb="42"/>
        <link type="nottaken" cfg="6" bb="44"/>
      </succ>
    </bb>
    <bb id="44">
      <inst addr="0x8738" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x873c" instr="add.w r3, r3, #1"/>
      <inst addr="0x8740" instr="str.w r3, [r7, #136] ; 0x88"/>
      <succ>
        <link type="nottaken" cfg="6" bb="45"/>
      </succ>
    </bb>
    <bb id="45">
      <inst addr="0x8744" instr="ldr r2, [r7, #32]"/>
      <inst addr="0x8746" instr="ldr.w r3, [r7, #136] ; 0x88"/>
      <inst addr="0x874a" instr="cmp r2, r3"/>
      <inst addr="0x874c" instr="bgt.w 85f0 initialiseLUdcmp+0x3c8"/>
      <succ>
        <link type="taken" cfg="6" bb="41"/>
        <link type="nottaken" cfg="6" bb="46"/>
      </succ>
    </bb>
    <bb id="46">
      <inst addr="0x8750" instr="ldr.w r3, [r7, #156] ; 0x9c"/>
      <inst addr="0x8754" instr="add.w r3, r3, #1"/>
      <inst addr="0x8758" instr="str.w r3, [r7, #156] ; 0x9c"/>
      <succ>
        <link type="nottaken" cfg="6" bb="47"/>
      </succ>
    </bb>
    <bb id="47">
      <inst addr="0x875c" instr="ldr r2, [r7, #32]"/>
      <inst addr="0x875e" instr="ldr.w r3, [r7, #156] ; 0x9c"/>
      <inst addr="0x8762" instr="cmp r2, r3"/>
      <inst addr="0x8764" instr="bgt.w 83ae initialiseLUdcmp+0x186"/>
      <succ>
        <link type="taken" cfg="6" bb="27"/>
        <link type="nottaken" cfg="6" bb="48"/>
      </succ>
    </bb>
    <bb id="48">
      <inst addr="0x8768" instr="mov r1, r4"/>
      <inst addr="0x876a" instr="add.w r2, r7, #32"/>
      <inst addr="0x876e" instr="mov.w r3, #104 ; 0x68"/>
      <inst addr="0x8772" instr="mov r0, r1"/>
      <inst addr="0x8774" instr="mov r1, r2"/>
      <inst addr="0x8776" instr="mov r2, r3"/>
      <inst addr="0x8778" instr="blx 255a0 memcpy"/>
      <inst addr="0x877c" instr="mov r0, r4"/>
      <inst addr="0x877e" instr="add.w r7, r7, #180 ; 0xb4"/>
      <inst addr="0x8782" instr="mov sp, r7"/>
      <inst addr="0x8784" instr="pop {r4, r7, pc}"/>
      <inst addr="0x8786" instr="nop"/>
      <succ>
      </succ>
    </bb>
  </cfg>
  <cfg id="7" name="solveLUdcmp">
    <bb id="49">
      <inst addr="0x8788" instr="sub sp, #16"/>